name: Deploy code
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
            uses: actions/setup-node@v3
            with:
                node-version: "16.x"
                - name: Install dependencies
                run: npm install
                - name: Build the code
                working directory: client
                run: npm run build
                - name: Deploy to firebase
                working directory: client
                uses: w9jds/firebase-action@master
                with:
                    args: deploy --only hosting
                    env:
                        PROJECT_PATH: ./out
                        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
                        - run: echo succesfully deployed to the firebase lmao
